In [52]:
import numpy as np

x = np.array([1,1,1],dtype=np.float)

In [53]:
x

array([1., 1., 1.])

In [54]:
np.shape(x)

(3,)

In [55]:
x.itemsize #32 bit floating point numbers

8

In [56]:
np.pi

3.141592653589793

In [59]:
?np.pi

In [7]:
np.sin(np.array([1,1,1],dtype=np.float32) )

array([0.84147096, 0.84147096, 0.84147096], dtype=float32)

In [60]:
x=np.array([ [1,2,3],[4,5,6] ])

In [61]:
np.shape(x)

(2, 3)

In [62]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
new = np.copy(x[0])

In [76]:
new[0] = 1.0

In [77]:
new

array([1, 2, 3])

In [78]:
x 

array([[0, 2, 3],
       [4, 5, 6]])

In [16]:
x[:,]

array([[3],
       [6]])

In [19]:
x=np.ones((3,3))

In [20]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
y = x

In [22]:
x[0,0]=999

In [23]:
x

array([[999.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [ ]:
y*x

In [31]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
x=np.matrix([[1],[0],[0]])

In [33]:
A*x

matrix([[1],
        [4],
        [7]])

In [34]:
np.dot(A,x)

matrix([[1],
        [4],
        [7]])

In [79]:
import numpy as np

a = np.array([1,2,6,7,4,6],dtype=float)

In [87]:
a[0:5:2]

array([1., 6., 4.])

In [94]:
a = np.arange(500)

In [107]:
a=a.reshape(5,2,-1)

In [108]:
a[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [112]:
a[:-2]

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
          86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 16

In [37]:
a[:-2]

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
          86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 16

In [113]:
a[::-1]  

array([[[400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411,
         412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423,
         424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435,
         436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447,
         448, 449],
        [450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461,
         462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473,
         474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485,
         486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497,
         498, 499]],

       [[300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
         312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323,
         324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335,
         336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347,
         348, 349],
        [350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361,
         362, 363, 364, 365, 366, 367, 36

In [114]:
a[:-11]

array([[[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173,
         174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185,
         186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197,
         198, 199]],

       [[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  6